### ISSUE TITLE
User Register Functionality

### ISSUE THREAD

**Issue by hardingadonis** [hardingadonis/miu-shop#21]
## Requirements
- Name servlet file is `RegisterServlet` with path `/register`.
- Name jsp file is `register.jsp`.
- CSS file will be placed in `css` folder.
- JS file will be placed in `js` folder.
- Information of user needs to get:
  - Full name.
  - Year of birthday.
  - Gender.
  - Email.
  - Password.

**Comment by GoldStarPro** [comment]
Tui tạo xong form đăng kí rồi. Đang xử lí chỗ Submit cái form để tạo tài khoản mới thành công.

**Comment by hardingadonis** [comment]
> Tui tạo xong form đăng kí rồi. Đang xử lí chỗ Submit cái form để tạo tài khoản mới thành công.

Ông đẩy lên để t coi thử, đấy nhánh mới á

**Comment by GoldStarPro** [comment]
Chỉ cách đẩy với. Tui đẩy nãy giờ không được :V

**Comment by hardingadonis** [comment]
> Chỉ cách đẩy với. Tui đẩy nãy giờ không được :V

Để ném google meet
